[package]
name = "plutonium"
version = "0.1.0"
authors = ["Max Orok <morok@mevex.com>"]
edition = "2018"
description = "Be safe out there"
license = "MIT OR Apache-2.0"

[dependencies]
syn = "1.0.14"
quote = "1.0.2"

[lib]
proc-macro = true
